alias: Turn off lights when I'm not home
trigger:
    - platform: state
      entity_id: group.all_devices
      from: 'home'
      to: 'not_home'
      state: 'not_home'
action:
    service: homeassistant.turn_off
    entity_id:
        - light.living_room_main
        - light.bedside
        - switch.desk_lamp
