alias: Turn on light at 8am on weekdays
trigger:
    - platform: time
      after: '08:00:00'
condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
action:
    service: homeassistant.turn_on
    entity_id: light.living_room_main
